RisePayTest/Controllers/ColaboradorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RisePayTest.Data;
using RisePayTest.Models;
using RisePayTest.Models.AuxiliaryModels;
using RisePayTest.Extensions;
namespace RisePayTest.Controllers
{
    public class ColaboradorController : Controller
    {
        private readonly AppDbContext _context;
        public ColaboradorController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var cargos = await _context.Cargos.ToListAsync();
            if (!cargos.Any())
            {
                await GenerateCargos();
            }
            return View();
        }

        public async Task<IActionResult> LoadTable(DtParameters dtParameters)
        {
            var searchBy = dtParameters.Search?.Value;

            var orderCriteria = "Id";
            var orderAscendingDirection = true;

            if (dtParameters.Order != null)
            {
                orderCriteria = dtParameters.Columns[dtParameters.Order[0].Column].Data;
                orderAscendingDirection = dtParameters.Order[0].Dir.ToString().ToLower() == "asc";
            }

            var result = (await _context.Colaboradores.Include(c => c.Cargo).ToListAsync()).AsQueryable();

            if (!string.IsNullOrEmpty(searchBy))
            {
                result = result.Where(r => r.Nome != null && r.Nome.ToUpper().Contains(searchBy.ToUpper()));
            }

            result = orderAscendingDirection ? result.OrderByDynamic(orderCriteria, DtOrderDir.Asc) : result.OrderByDynamic(orderCriteria, DtOrderDir.Desc);

            var filteredResultsCount = result.Count();
            var totalResultsCount = await _context.Colaboradores.CountAsync();

            if(dtParameters.Length == -1)
            {
                dtParameters.Length = filteredResultsCount;
            }

            return Json(new DtResult<Colaborador>
            {
                Draw = dtParameters.Draw,
                RecordsTotal = totalResultsCount,
                RecordsFiltered = filteredResultsCount,
                Data = result
                    .Skip(dtParameters.Start)
                    .Take(dtParameters.Length)
                    .ToList()
            });
        }
        public async Task<IActionResult> Create()
        {
            ViewData["Cargos"] = await _context.Cargos.ToListAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Nome,Email,Telefone,IdCargo")] Colaborador colaborador)
        {
            ViewData["Cargos"] = await _context.Cargos.ToListAsync();

            ModelState.Remove("Cargo");
            if (!ModelState.IsValid)
            {
                return View(colaborador);
            }

            _context.Add(colaborador);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            ViewData["Cargos"] = await _context.Cargos.ToListAsync();
            var colaborador = await _context.Colaboradores.FindAsync(id);
            if(colaborador == null)
            {
                return NotFound();
            } 
            return View(colaborador);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind("Id,Nome,Email,Telefone,IdCargo")] Colaborador colaborador)
        {
            ModelState.Remove("Cargo");
            if (!ModelState.IsValid)
            {
                
                return View(colaborador);
            }

            _context.Update(colaborador);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));



        }

        private async Task GenerateCargos()
        {
            List<Cargo> novosCargos = 
                [
                    new Cargo() { Nome = "Analista"},
                    new Cargo() { Nome = "Suporte"},
                    new Cargo() { Nome = "DBA"},
                    new Cargo() { Nome = "Administrador de Rede"}
                ];
            foreach(var cargo in novosCargos)
            {
                _context.Add(cargo);
                await _context.SaveChangesAsync();
            }
        }
    }


}

RisePayTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RisePayTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RisePayTest.styles.css" asp-append-version="true" />
    <link href="~/lib/DataTables/css/datatables.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RisePayTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Colaborador" asp-action="Index">Colaboradores</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- Modal Global -->
    <div class="modal fade" id="modal-global" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="" id="global-modal-body">
                    
                </div>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RisePayTest - <a asp-area="" asp-controller="Colaborador" asp-action="Index">Colaboradores</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/DataTables/js/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>